version: '2'

services:
    web:
        build: .
        ports:
            - "8037:80"
        volumes:
            - ./public:/var/www/html/
            - .:/var/www/
        links:
            - db:db
    db:
        image: mariadb:10.3.28
#        volumes:
#            - ./var/mysql:/var/lib/mysql
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root

    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "9037:80"
        links:
            - db:db
        environment:
            - UPLOAD_LIMIT=256M